### ISSUE TITLE
Any .it file created containing _define will cause client crashes

### ISSUE THREAD

**Issue by PoiDoex8** [regomne/mabi-pack2#3]
data\material\_define\..
any .it file created containing this will cause a crash on client upon load.
removing this folder and repacking removes the crash
this folder and its contents are needed to create custom textures and such.

**Comment by regomne** [comment]
I tested and found it not crashing when I packed data_00494 which contains `data/material/_define/material...` files.
Could you upload the files that needs packing?

**Comment by shaggyze** [comment]
> Could you upload the files that needs packing?
https://dl.dropboxusercontent.com/s/qd5h9wzrbcw2fob/data.zip

Also, we are on North American Mabinogi and I do know of at least one person that says they don't crash when packing said files either, the files work with data folder enabled so unsure if it's the client, the packer, or some windows version/updates causing the issue.

Most likely repeating the process without changing anything will result in you not crashing again and testing on virtual machines with various windows builds on NA Mabinogi would be necessary as it will probably be the only thing that may give us some insight.

**Comment by regomne** [comment]
[data_99999.zip](https://github.com/regomne/mabi-pack2/files/8361376/data_99999.zip)

You may have a try on NA Mabinogi. I have tested it on CN Mabinogi and it worked.

Hint: Are the file name of the packed .it file correct? It can only be like XXXX_YYYY.it, where XXXX are any number of characters and YYYY must be any number of digits. For example: data_12345.it, zzz_0.it, patch-of-name_1.it and so on.

Hint2: File name which is used in packing must not be modified. Only repacking is allowed if you want to rename it.

**Comment by shaggyze** [comment]
> You may have a try on NA Mabinogi. I have tested it on CN Mabinogi and it worked.

We were aware of both Hints, I did not create this issue because I doubted it was mabi-pack2 due to the fact I know of one other person who has packed this mod specifically and it worked fine for them on NA Mabinogi, they were also able to create a .it with the data\xml\ and data\code\ folders that memory patcher's Enable Data Folder Read uses, and he also sent them to me to test (at which point I also crashed), we have to place them in the data\local\ folder for us not to crash.

However the .it you sent does not seem to be crashing me now, most likely because we are on version 2 now and it is not being applied or is being overwritten by Mabinogi’s .it’s, will rebuild mabi-pack2 to determine that, and would like to have version and compression added to the CLI arguments whenever you have time.

**Comment by PoiDoex8** [comment]
powershell> .\mabi-pack2.exe pack -i .\temp\ -o sight_00001.it
powershell> .\mabi-pack2.exe list -i .\sight_00001.it
data\gfx\fx\effect\g23_specialization.xml
data\material\fx\effect\Blue.dds
data\material\fx\effect\Metallurgy.dds
data\material\fx\effect\Yellow.dds
data\material\_define\material\effect\Blue.xml
data\material\_define\material\effect\Metallurgy.xml
data\material\_define\material\effect\Yellow.xml

this works now but only if i delete the "data" folder from the mabi install that contains the same files.
must be some kinda of mabi issue its self

files contained in data\material\\_define\ can not be in \data in the root of mabi and inside a .it file at same time
if both are present client will crash on load

**Comment by regomne** [comment]
> would like to have version and compression added to the CLI arguments

@shaggyze It seems that the .it files don't have a version like .pack. Game reads all .it files by filename-order.

mabi-pack2 supports compression of some file types (including `txt xml dds pmg set`). You can commit issues for more types.
